"""empty message

Revision ID: 91e082f3432f
Revises: 
Create Date: 2025-01-27 10:05:14.792652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e082f3432f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
         batch_op.add_column(sa.Column('bill_id', sa.Integer(), sa.ForeignKey('bill.id', name='fk_payment_history_bill_id'), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_history', schema=None) as batch_op:
          batch_op.drop_column('bill_id')
    # ### end Alembic commands ###
